import { useState, useEffect } from 'react'
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  Platform, StatusBar, Share, Alert, ActivityIndicator,
} from 'react-native'
import { router } from 'expo-router'
import { database } from '../../../src/db/database'
import type { Patient } from '../../../src/db/models/Patient'
import type { Task } from '../../../src/db/models/Task'
import type { LabReport } from '../../../src/db/models/LabReport'
import { Q } from '@nozbe/watermelondb'
import { colors, typography, spacing, radius, shadow } from '../../../src/theme'

// ─── Types ─────────────────────────────────────────────────────────────────────
interface PatientSummary {
  patient: Patient
  pendingTasks: Task[]
  abnormalLabs: LabReport[]
}

// ─── Handover builder ──────────────────────────────────────────────────────────
async function buildHandover(): Promise<{ summaries: PatientSummary[]; text: string }> {
  const now = Date.now()
  const sevenDaysAgo = now - 7 * 24 * 60 * 60 * 1000

  const patients = await database.get<Patient>('patients')
    .query(Q.where('status', Q.notEq('DISCHARGED')))
    .fetch()

  // Sort: CRITICAL first, then ADMITTED
  patients.sort((a, b) => {
    if (a.status === 'CRITICAL' && b.status !== 'CRITICAL') return -1
    if (b.status === 'CRITICAL' && a.status !== 'CRITICAL') return 1
    return 0
  })

  const summaries: PatientSummary[] = await Promise.all(
    patients.map(async (p) => {
      const pendingTasks = await database.get<Task>('tasks')
        .query(Q.where('patient_id', p.id), Q.where('status', Q.notEq('DONE')))
        .fetch()
      const abnormalLabs = await database.get<LabReport>('lab_reports')
        .query(
          Q.where('patient_id', p.id),
          Q.where('is_abnormal', true),
          Q.where('reported_at', Q.gte(sevenDaysAgo)),
        )
        .fetch()
      return { patient: p, pendingTasks, abnormalLabs }
    })
  )

  // Build text report
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })
  const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })

  const lines: string[] = [
    `HANDOVER REPORT`,
    `${date} · ${time}`,
    `Generated by MedLog AI`,
    `${'═'.repeat(42)}`,
    '',
  ]

  summaries.forEach((s, i) => {
    const p = s.patient
    const label = p.status === 'CRITICAL' ? '🔴 CRITICAL' : '🟢 ADMITTED'
    lines.push(`${i + 1}. ${p.name ?? `MR# ${p.mrNumber}`} — ${label}`)
    if (p.name) lines.push(`   MR# ${p.mrNumber}`)
    if (p.wardId || p.bedNumber) lines.push(`   ${[p.wardId ? `Ward ${p.wardId}` : null, p.bedNumber ? `Bed ${p.bedNumber}` : null].filter(Boolean).join(', ')}`)
    if (p.admissionDiagnosis) lines.push(`   Dx: ${p.admissionDiagnosis}`)
    if (p.phone) lines.push(`   📞 ${p.phone}`)

    if (s.abnormalLabs.length > 0) {
      lines.push(``)
      lines.push(`   🧪 Abnormal labs:`)
      s.abnormalLabs.slice(0, 5).forEach(l => {
        const flag = l.isCritical ? '⚠️ CRITICAL' : '↑↓ ABNORMAL'
        lines.push(`   • ${l.testName}: ${l.value} ${l.unit} [${flag}]`)
      })
    }

    if (s.pendingTasks.length > 0) {
      lines.push(``)
      lines.push(`   ✅ Pending tasks (${s.pendingTasks.length}):`)
      s.pendingTasks.slice(0, 5).forEach(t => {
        const due = t.dueAt ? ` — due ${new Date(t.dueAt).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}` : ''
        lines.push(`   • [${t.priority}] ${t.title}${due}`)
      })
    }

    if (p.followUpDate) {
      lines.push(``)
      lines.push(`   📅 Follow-up: ${new Date(p.followUpDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`)
      if (p.followUpNotes) lines.push(`   Notes: ${p.followUpNotes}`)
    }

    lines.push('')
    lines.push(`   ${'─'.repeat(38)}`)
    lines.push('')
  })

  const totalPending = summaries.reduce((acc, s) => acc + s.pendingTasks.length, 0)
  const totalAbnormal = summaries.reduce((acc, s) => acc + s.abnormalLabs.length, 0)

  lines.push(`${'═'.repeat(42)}`)
  lines.push(`SUMMARY: ${patients.length} patients | ${summaries.filter(s => s.patient.status === 'CRITICAL').length} critical`)
  lines.push(`Pending tasks: ${totalPending} | Abnormal labs: ${totalAbnormal}`)
  lines.push(``)
  lines.push(`Please review all critical patients immediately.`)
  lines.push(`— MedLog AI`)

  return { summaries, text: lines.join('\n') }
}

// ─── Screen ────────────────────────────────────────────────────────────────────
export default function HandoverScreen() {
  const [summaries, setSummaries] = useState<PatientSummary[]>([])
  const [reportText, setReportText] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    buildHandover().then(({ summaries, text }) => {
      setSummaries(summaries)
      setReportText(text)
      setLoading(false)
    }).catch(() => setLoading(false))
  }, [])

  async function handleShare() {
    try {
      await Share.share({ message: reportText, title: 'Handover Report — MedLog AI' })
    } catch {
      Alert.alert('Error', 'Could not share report')
    }
  }

  const now = new Date()
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })

  if (loading) {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.screenBg }}>
        <ActivityIndicator color={colors.primary} size="large" />
        <Text style={{ color: colors.gray500, marginTop: spacing.md }}>Building handover report…</Text>
      </View>
    )
  }

  const totalTasks = summaries.reduce((a, s) => a + s.pendingTasks.length, 0)
  const totalAbnormal = summaries.reduce((a, s) => a + s.abnormalLabs.length, 0)
  const critical = summaries.filter(s => s.patient.status === 'CRITICAL').length

  return (
    <View style={styles.root}>
      <StatusBar barStyle="light-content" backgroundColor={colors.primaryDark} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
          <Text style={styles.backText}>{'<'}</Text>
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle}>Handover Report</Text>
          <Text style={styles.headerSub}>{dateStr} · {timeStr}</Text>
        </View>
        <TouchableOpacity style={styles.shareBtn} onPress={handleShare} activeOpacity={0.85}>
          <Text style={styles.shareIcon}>⬆</Text>
          <Text style={styles.shareBtnText}>Share</Text>
        </TouchableOpacity>
      </View>

      {/* Summary bar */}
      <View style={styles.summaryBar}>
        <SummaryPill value={summaries.length} label="Patients" color={colors.primary} />
        <SummaryPill value={critical} label="Critical" color={colors.danger} />
        <SummaryPill value={totalTasks} label="Tasks" color={colors.warning} />
        <SummaryPill value={totalAbnormal} label="Abn. labs" color="#7C3AED" />
      </View>

      {summaries.length === 0 ? (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
          <Text style={{ fontSize: 40, marginBottom: spacing.lg, opacity: 0.3 }}>🏥</Text>
          <Text style={typography.h3}>No active patients</Text>
          <Text style={{ ...typography.bodySmall, marginTop: spacing.sm }}>Add patients to generate a handover</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>

          {summaries.map((s, i) => {
            const p = s.patient
            const isCritical = p.status === 'CRITICAL'

            return (
              <View key={p.id} style={[styles.patientCard, isCritical && styles.patientCardCritical]}>

                {/* Patient header */}
                <View style={styles.patientHeader}>
                  <View style={[styles.patientNumBadge, { backgroundColor: isCritical ? colors.danger : colors.primary }]}>
                    <Text style={styles.patientNumText}>{i + 1}</Text>
                  </View>
                  <View style={{ flex: 1 }}>
                    <View style={{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }}>
                      <Text style={styles.patientName}>{p.name ?? `MR# ${p.mrNumber}`}</Text>
                      {isCritical && (
                        <View style={styles.criticalTag}>
                          <Text style={styles.criticalTagText}>🔴 CRITICAL</Text>
                        </View>
                      )}
                    </View>
                    <View style={{ flexDirection: 'row', gap: spacing.sm, marginTop: 2 }}>
                      {p.name && <Text style={styles.patientMeta}>MR# {p.mrNumber}</Text>}
                      {p.wardId && <Text style={styles.patientMeta}>Ward {p.wardId}</Text>}
                      {p.bedNumber && <Text style={styles.patientMeta}>Bed {p.bedNumber}</Text>}
                      {p.phone && <Text style={styles.patientMeta}>📞 {p.phone}</Text>}
                    </View>
                    {p.admissionDiagnosis && (
                      <Text style={styles.patientDx} numberOfLines={2}>{p.admissionDiagnosis}</Text>
                    )}
                  </View>
                  <TouchableOpacity onPress={() => router.push(`/(app)/patients/${p.id}` as any)} activeOpacity={0.7}>
                    <Text style={styles.viewBtn}>Open →</Text>
                  </TouchableOpacity>
                </View>

                {/* Abnormal labs */}
                {s.abnormalLabs.length > 0 && (
                  <View style={styles.section}>
                    <Text style={styles.sectionTitle}>🧪 Abnormal Labs</Text>
                    {s.abnormalLabs.map(lab => (
                      <View key={lab.id} style={styles.labRow}>
                        <View style={[styles.labFlag, { backgroundColor: lab.isCritical ? colors.dangerLight : colors.warningLight }]}>
                          <Text style={[styles.labFlagText, { color: lab.isCritical ? colors.danger : colors.warning }]}>
                            {lab.isCritical ? 'CRIT' : 'ABN'}
                          </Text>
                        </View>
                        <Text style={styles.labName}>{lab.testName}</Text>
                        <Text style={[styles.labValue, { color: lab.isCritical ? colors.danger : colors.warning }]}>
                          {lab.value} {lab.unit}
                        </Text>
                      </View>
                    ))}
                  </View>
                )}

                {/* Pending tasks */}
                {s.pendingTasks.length > 0 && (
                  <View style={styles.section}>
                    <Text style={styles.sectionTitle}>✅ Pending Tasks ({s.pendingTasks.length})</Text>
                    {s.pendingTasks
                      .sort((a, b) => {
                        const order: Record<string, number> = { URGENT: 0, HIGH: 1, MEDIUM: 2, LOW: 3 }
                        return (order[a.priority] ?? 4) - (order[b.priority] ?? 4)
                      })
                      .map(task => {
                        const priorityColor: Record<string, string> = { URGENT: '#7C3AED', HIGH: colors.danger, MEDIUM: colors.warning, LOW: colors.gray400 }
                        const color = priorityColor[task.priority] ?? colors.gray400
                        return (
                          <View key={task.id} style={styles.taskRow}>
                            <View style={[styles.taskPriority, { backgroundColor: color + '20', borderColor: color }]}>
                              <Text style={[styles.taskPriorityText, { color }]}>{task.priority[0]}</Text>
                            </View>
                            <View style={{ flex: 1 }}>
                              <Text style={styles.taskTitle}>{task.title}</Text>
                              {task.dueAt ? (
                                <Text style={[styles.taskDue, task.dueAt < Date.now() ? { color: colors.danger } : {}]}>
                                  {task.dueAt < Date.now() ? '⚠️ Overdue · ' : 'Due '}
                                  {new Date(task.dueAt).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                                </Text>
                              ) : null}
                            </View>
                          </View>
                        )
                      })}
                  </View>
                )}

                {/* No tasks or labs */}
                {s.pendingTasks.length === 0 && s.abnormalLabs.length === 0 && (
                  <View style={styles.section}>
                    <Text style={{ fontSize: 13, color: colors.gray400, fontStyle: 'italic' }}>No pending tasks or abnormal labs ✓</Text>
                  </View>
                )}

                {/* Follow-up */}
                {p.followUpDate && (
                  <View style={[styles.section, { borderTopWidth: 0 }]}>
                    <View style={styles.followUpRow}>
                      <Text style={styles.followUpIcon}>📅</Text>
                      <View>
                        <Text style={styles.followUpLabel}>Follow-up scheduled</Text>
                        <Text style={styles.followUpDate}>
                          {new Date(p.followUpDate).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}
                          {p.followUpDate < Date.now() ? ' (Overdue)' : ''}
                        </Text>
                        {p.followUpNotes ? <Text style={styles.followUpNotes}>{p.followUpNotes}</Text> : null}
                      </View>
                    </View>
                  </View>
                )}
              </View>
            )
          })}

          {/* Share button at bottom */}
          <TouchableOpacity style={styles.shareBottomBtn} onPress={handleShare} activeOpacity={0.85}>
            <Text style={styles.shareBottomIcon}>⬆</Text>
            <Text style={styles.shareBottomText}>Share Handover via WhatsApp / Copy</Text>
          </TouchableOpacity>

          <View style={{ height: 40 }} />
        </ScrollView>
      )}
    </View>
  )
}

function SummaryPill({ value, label, color }: { value: number; label: string; color: string }) {
  return (
    <View style={[pill.wrap, value > 0 && { borderColor: color, borderWidth: 1.5 }]}>
      <Text style={[pill.value, { color: value > 0 ? color : colors.gray400 }]}>{value}</Text>
      <Text style={pill.label}>{label}</Text>
    </View>
  )
}

const pill = StyleSheet.create({
  wrap: { flex: 1, alignItems: 'center', backgroundColor: colors.white, borderRadius: radius.md, paddingVertical: spacing.sm, borderWidth: 1, borderColor: colors.gray200, marginHorizontal: 2 },
  value: { fontSize: 20, fontWeight: '800', letterSpacing: -0.5 },
  label: { fontSize: 10, color: colors.gray400, fontWeight: '600', marginTop: 1 },
})

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.screenBg },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingTop: Platform.OS === 'ios' ? 52 : 36,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.xl,
    gap: spacing.md,
  },
  backBtn: { width: 36, height: 36, borderRadius: radius.full, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  backText: { fontSize: 20, color: colors.white, fontWeight: '600' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: colors.white },
  headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 1 },
  shareBtn: { flexDirection: 'column', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  shareIcon: { fontSize: 16, color: colors.white },
  shareBtnText: { fontSize: 11, fontWeight: '800', color: colors.white },

  summaryBar: { flexDirection: 'row', backgroundColor: colors.white, padding: spacing.md, gap: spacing.xs, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.gray200, ...shadow.sm },

  scroll: { padding: spacing.lg },

  patientCard: { backgroundColor: colors.white, borderRadius: radius.lg, marginBottom: spacing.lg, overflow: 'hidden', ...shadow.sm },
  patientCardCritical: { borderWidth: 2, borderColor: colors.danger + '60' },

  patientHeader: { flexDirection: 'row', alignItems: 'flex-start', padding: spacing.lg, gap: spacing.md, backgroundColor: colors.screenBg },
  patientNumBadge: { width: 28, height: 28, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  patientNumText: { fontSize: 13, fontWeight: '800', color: colors.white },
  patientName: { fontSize: 16, fontWeight: '800', color: colors.gray900 },
  patientMeta: { fontSize: 11, color: colors.gray500, fontWeight: '500' },
  patientDx: { fontSize: 13, color: colors.textMid, marginTop: 3, fontStyle: 'italic' },
  criticalTag: { backgroundColor: colors.dangerLight, borderRadius: radius.sm, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  criticalTagText: { fontSize: 10, fontWeight: '800', color: colors.danger },
  viewBtn: { fontSize: 13, fontWeight: '600', color: colors.primary },

  section: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.gray100 },
  sectionTitle: { fontSize: 12, fontWeight: '800', color: colors.gray500, letterSpacing: 0.5, marginBottom: spacing.sm, textTransform: 'uppercase' },

  labRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.xs },
  labFlag: { borderRadius: radius.sm, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  labFlagText: { fontSize: 10, fontWeight: '800', letterSpacing: 0.3 },
  labName: { flex: 1, fontSize: 14, color: colors.gray700, fontWeight: '500' },
  labValue: { fontSize: 14, fontWeight: '800' },

  taskRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md, marginBottom: spacing.sm },
  taskPriority: { width: 24, height: 24, borderRadius: radius.full, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  taskPriorityText: { fontSize: 11, fontWeight: '800' },
  taskTitle: { fontSize: 14, color: colors.text, fontWeight: '500' },
  taskDue: { fontSize: 12, color: colors.gray400, marginTop: 1 },

  followUpRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md },
  followUpIcon: { fontSize: 18, marginTop: 2 },
  followUpLabel: { fontSize: 12, fontWeight: '700', color: colors.gray500, textTransform: 'uppercase', letterSpacing: 0.5 },
  followUpDate: { fontSize: 14, fontWeight: '700', color: colors.gray900, marginTop: 2 },
  followUpNotes: { fontSize: 13, color: colors.gray500, marginTop: 2, fontStyle: 'italic' },

  shareBottomBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    paddingVertical: 15,
    marginTop: spacing.sm,
    ...shadow.md,
  },
  shareBottomIcon: { fontSize: 18, color: colors.white },
  shareBottomText: { fontSize: 15, fontWeight: '700', color: colors.white },
})
